[package]
name = "skipidy"
version = "0.1.0"
edition = "2024"

description = "A skiplist implementation"
categories = ["data-structures"]
keywords = ["collection", "skiplist", "sorted"]

repository = "https://gitlab.com/ltungv/skipidy"
license = "MIT"

[dependencies]
rand = "0.9.2"
